# Generated by Django 3.0.2 on 2020-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200831_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='fix_id',
        ),
        migrations.AddField(
            model_name='page',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
